### ISSUE TITLE
Add cake-contrib user

### ISSUE THREAD

**Issue by gep13** [kjjuno/repo-version#55]
**Is your feature request related to a problem? Please describe.**
No, not related to a problem.

**Describe the solution you'd like**
First of all, I wanted to thank you for adding to the Cake community by adding this addin.

I was just wondering if you had seen this blog post:

http://cakebuild.net/blog/2016/08/cake-contribution-organization

We are currently going through a process of increasing the visibility of addins, and also trying to ensure their long term maintainability.

To that end, we are asking addin creators to add the cake-contrib user on NuGet as a co-owner (this can be done through the NuGet website by clicking on Manage Owners on the package page).

Would you be interested in doing this? If you have any questions about this, please let me know. There was some initial concern that the Cake Team were trying to "take over" packages, and that couldn't be further from the truth, and if you have this concern, or others, I would like to address them.

Thanks!

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by kjjuno** [comment]
Done

**Comment by kjjuno** [comment]
I'm not totally convinced about moving the source to the organization yet. Maybe once I hit the 1.0 release I will consider it.

**Comment by gep13** [comment]
@kijuno thank you for doing that, I appreciate it!

Moving to the Cake Contrib Organisation is certainly not a requirement, so that is not a problem. There are good reasons to do it, some of which we touch on in the blog post, so I can definitely follow up with this later, if this is something which you would consider.

**Comment by kjjuno** [comment]
I'm planning to move Cake.RepoVersion to its own repository. I will be happy to move that into the cake organization.

**Comment by gep13** [comment]
>@kjjuno said...
I'm planning to move Cake.RepoVersion to its own repository. I will be happy to move that into the cake organization.

That sounds perfect, and we would be happy to have it in the Cake Contrib Organisation when it is ready

**Comment by kjjuno** [comment]
https://github.com/kjjuno/repo-version/pull/56 officially moves Cake.RepoVersion to https://github.com/kjjuno/Cake.RepoVersion

@gep13 This should be ready to move over to the Cake Contrib Organisation. From what I've ready I should transfer that repo to you correct?

**Comment by gep13** [comment]
@kjjuno wow, that was quick! 😄 

Yes, due to a limitation on GitHub about "who" can transfer repositories into an Organisation, the repository first needs to be transferred to someone who is an owner of the Organisation (i.e. someone on the Cake Team) and then they can move it into the Organisation.  If you wanted to transfer it to my account (gep13) then I can take care of this, and get you set up with the necessary permissions, etc.
